syntax = "proto3";

import "cif_common.proto";
//The CIF protos are installed in the default CIF data directory.  On Windows this is C:/Users/Public/Documents/CIF/protos
//When generating new gRPC server/client code this directory needs to be provided as an Import path

package cif.tag_monitor;

// This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

service TagMonitor {
  rpc GetDoubleTagValues (TagValueRequest) returns (DoubleTagValueResponse) {}
}

message TagValueRequest {
   repeated string tags = 1;
}

message DoubleTagValueResponse {
   repeated double tag_values = 1;
   cif.common.Status status = 2;
}