syntax = "proto3";

import "cif_common.proto";
import "cif_management_common.proto";

package cif.manager;

service Manager {
  // Load a specific plugin instance.
  rpc LoadPlugin (LoadPluginRequest) returns (LoadPluginResponse) {}
  // Plugin calls this to register itself with the manager.
  rpc RegisterPlugin (RegisterPluginRequest) returns (RegisterPluginResponse) {}
  // Plugin calls this to unregister itself with the manager.
  rpc UnregisterPlugin (UnregisterPluginRequest) returns (UnregisterPluginResponse) {}
  // Gets the names of all Plugin Types on the system.
  rpc QueryPluginTypes (QueryPluginTypesRequest) returns (QueryPluginTypesResponse) {}
   // Aborts a plugin.  This should only be used if a plug-in is not responding to normal commands.
  rpc AbortPlugin (AbortPluginRequest) returns (AbortPluginResponse) {}
  // Unload all the instantiated plugins. If the plugins are running it will attempt to stop them.
  rpc UnloadAllPlugins (AbortAllPluginsRequest) returns (AbortAllPluginsResponse) {}
  // Destroy the manager.  If plugins are running it will attempt to stop them.  
  rpc Destroy (DestroyRequest) returns (DestroyResponse) {}
  // Ping the manager.  
  rpc Ping (PingRequest) returns (PingResponse) {}
  // Query the errors occurred.
  rpc QueryErrors (QueryErrorsRequest) returns (QueryErrorsResponse) {}
  // Query the config from the log.
  rpc QueryConfig (QueryConfigRequest) returns (QueryConfigResponse) {}
  // Query the info from the log.
  rpc QueryInfo (QueryInfoRequest) returns (QueryInfoResponse) {}
  // Reset the filter time for returned errors. 
  rpc ResetErrorIndex (ResetErrorIndexRequest) returns (ResetErrorIndexResponse) {}
  // Reset the filter time for returned configuration. 
  rpc ResetConfigIndex (ResetConfigIndexRequest) returns (ResetConfigIndexResponse) {}
  // Reset the filter time for returned information. 
  rpc ResetInfoIndex (ResetInfoIndexRequest) returns (ResetInfoIndexResponse) {}
  // Gets the name, type, status, and gRPC port of all loaded plugins.
  rpc QueryPluginInfo (QueryPluginInfoRequest) returns (QueryPluginInfoResponse) {}
  // Gets the name, type, status, and gRPC port of loaded plugin by name.
  rpc QueryPlugin (QueryPluginRequest) returns (QueryPluginResponse) {}
  // Provides the plugin status and requests system status.
  rpc QuerySystemStatus (QuerySystemStatusRequest) returns (QuerySystemStatusResponse) {}
  // Updates a tracked clock with a new timestamp pair or a reset.
  rpc UpdateClock (UpdateClockRequest) returns (UpdateClockResponse) {}
  // Create orchestration file from logged configuration.
  rpc CreateOrch (CreateOrchRequest) returns (CreateOrchResponse) {}
  // Query the errors occurred.
  rpc QueryClockStatus (QueryClockStatusRequest) returns (QueryClockStatusResponse) {}
  // Query all channels on the system matching the filter.  Filter parameters are AND to pass.  
  rpc QueryAllChannels (QueryAllChannelsRequest) returns (QueryAllChannelsResponse) {}
  // The loader calls this to register itself with the manager.
  rpc RegisterPluginLoader (RegisterPluginLoaderRequest) returns (RegisterPluginLoaderResponse) {}
  // The loader calls this to unregister itself with the manager.
  rpc UnregisterPluginLoader (UnregisterPluginLoaderRequest) returns (UnregisterPluginLoaderResponse) {}
  // Manually create a new plugin loader.
  rpc CreatePluginLoader (CreatePluginLoaderRequest) returns (CreatePluginLoaderResponse) {}
  // Manually destroy an existing plugin loader.
  rpc DestroyPluginLoader (DestroyPluginLoaderRequest) returns (DestroyPluginLoaderResponse) {}
  // Gets the name, type, PID, and gRPC port of all registered plugin loaders.
  rpc QueryPluginLoaders (QueryPluginLoadersRequest) returns (QueryPluginLoadersResponse) {}
}

message LoadPluginRequest {
  string plugin_type = 1; //Name of the plugin type
  string plugin_name = 2; //Assigned name for the plugin instance.  Must be unique in the system.  
  string version = 3; //Optional string for version.  Format should be x.x.x (major, minor, fix).  Any missing entries will default to latest available on target.  For example 1.2 would default to the latest fix on the target of major 1, minor 2.
  string loader_process = 4; //Options string to specify what process to use to load the plugin, supported by some loaders.
}

message LoadPluginResponse {
  cif.common.Status status = 1;
}

message	RegisterPluginRequest {
  string plugin_name = 1;
  int32 grpc_port = 2;
  cif.common.ShortVersion plugin_version = 3;
}

message RegisterPluginResponse {
  string loader_name = 1;
}

message	UnregisterPluginRequest {
  string plugin_name = 1;
  repeated string unregister_channels = 2;
}

message UnregisterPluginResponse {}

message QueryPluginTypesRequest {
  bool reload = 1;
}

message	QueryPluginTypesResponse {
  repeated PluginType plugin_types = 1;
}

message AbortPluginRequest {
  string plugin_name = 1;
}

message AbortPluginResponse {
  cif.common.Status status = 1;
}

message AbortAllPluginsRequest {}

message AbortAllPluginsResponse {
  cif.common.Status status = 1;
}

message DestroyRequest {}

message DestroyResponse {}

message PingRequest {}

message PingResponse {
  cif.common.Status status = 1;
}

message QueryErrorsRequest {
  QuerySettings query_settings = 1;
}

message QueryErrorsResponse {
  ErrorInfoList error_info_list = 1;
}

message QueryConfigRequest {
  QuerySettings query_settings = 1;
}

message QueryConfigResponse {
  FileData file_data = 1;
}

message QueryInfoRequest {
  QuerySettings query_settings = 1;
}

message QueryInfoResponse {
  FileData file_data = 1;
}

message ResetErrorIndexRequest {}

message ResetErrorIndexResponse {
  cif.common.Status status = 1;
}

message ResetConfigIndexRequest {}

message ResetConfigIndexResponse {
  cif.common.Status status = 1;
}

message ResetInfoIndexRequest {}

message ResetInfoIndexResponse {
  cif.common.Status status = 1;
}

message QueryPluginInfoRequest {}

message QueryPluginInfoResponse {
  PluginInfoArray plugin_info_array = 1;
}

message QueryPluginRequest {
  string plugin_name = 1;
}

message QueryPluginResponse {
  PluginInfo plugin_info = 1;
  cif.common.Status status = 2;
}

message QuerySystemStatusRequest {
  PluginStatus plugin_status = 1;
}

message QuerySystemStatusResponse {
  SystemStatus system_status = 1;
}

message UpdateClockRequest {
  uint32 clock_id = 1;
  TimePair timestamp_pair = 2; 
  bool reinit = 3;
  string clock_name = 4;
}

message UpdateClockResponse {
  cif.common.Status status = 1;
}

message CreateOrchRequest {
  uint64 start_timestamp = 1; // If non-zero will get all config and filter from this timestamp.  If zero will build since latest config reset
  bool create_file = 2; // Determine if file we be created on target
  OrchestrationLanguage orchestration_language = 3; // Only Python supported currently
  string filename = 4; // File name.  Should be format "name.py"
  string default_ip = 5; // If not empty will set as the IP address for the python script.  If empty will set as first IPv4 address from target
}

message CreateOrchResponse {
  string orchestration_script = 1;
  cif.common.Status status = 2;
}

message QueryClockStatusRequest {}

message QueryClockStatusResponse {
  ClockStatusArray clock_status_array = 1;
}

message QueryAllChannelsRequest {
  cif.management_common.ChannelFilter channel_filter = 1;
}

message QueryAllChannelsResponse {
  cif.management_common.Channels channels = 1;
}

message RegisterPluginLoaderRequest {
  cif.management_common.LoaderInfoFull loader_info = 1;
}

message RegisterPluginLoaderResponse {
}

message CreatePluginLoaderRequest {
  cif.management_common.LoaderInfo loader_info = 1;
}

message CreatePluginLoaderResponse {
  cif.common.Status status = 1;
}

message DestroyPluginLoaderRequest {
  string loader_name = 1;
}

message DestroyPluginLoaderResponse {
  cif.common.Status status = 1;
}

message UnregisterPluginLoaderRequest {
  string loader_name = 1;
}

message UnregisterPluginLoaderResponse {
}

message QueryPluginLoadersRequest {
}

message QueryPluginLoadersResponse {
  repeated cif.management_common.LoaderInfoFull plugin_loaders_info = 1;
}

message	PluginType {
  string plugin_type = 1;
  cif.common.ShortVersion plugin_version = 2;
  cif.management_common.PluginMetadata plugin_metadata = 3;
  repeated string relative_path = 4; //Array of the relative path of the plugin in the plugin folder
}

message ErrorInfoList {
  repeated ErrorInfo error_info = 1;
}

message ErrorInfo {
  bool error_status = 1;
  int32 error_code = 2;
  string plugin = 3;
  string time = 4;
  string message = 5;
  string location = 6;
}

message QuerySettings {
  bool query_all = 1;
}

message FileData {
    string data = 1;
}

message PluginInfo {
  string plugin_name = 1;
  string plugin_type = 2;
  int32 grpc_port = 3;
  cif.common.ShortVersion plugin_version = 4;
  cif.management_common.PluginStatusData status = 5;
  cif.management_common.LoaderInfo loader_info = 6;
}

message PluginInfoArray {
  repeated PluginInfo plugin_info = 1;
}

message PluginStatus {
  string pluginname = 1;
  cif.management_common.PluginStatusData status = 2;
  cif.management_common.Channels channels = 3;
}

message TimePair {
  int64 system_time = 1;
  int64 external_time = 2;
}

message ClockConversion {
  uint32 clock_id = 1;
  int64 last_reset = 2;
  double slope = 3;
  TimePair offset_pair = 4; 
  string clock_name = 5;
}

message ClockConversionArray {
  repeated ClockConversion clock_conversions = 1;
}

message SystemStatus {
  ClockConversionArray clock_conversion_array = 1;
}

message ClockStatusArray {
  repeated ClockStatus clocks_status = 1;
}

message ClockStatus {
  ClockConversion clock_conversion = 1;
  int64 error_mean = 2;
  int64 error_std_dev = 3;
}

enum OrchestrationLanguage {
  ORCHESTRATIONLANGUAGE_UNKNOWN = 0;
  ORCHESTRATIONLANGUAGE_PYTHON = 1;
  }




