syntax = "proto3";

import "cif_common.proto";
import "cif_management_common.proto";

package cif.pluginloader;

service PluginLoader {
  // Load a specific plugin instance.
  rpc LoadPlugin (LoadPluginRequest) returns (LoadPluginResponse) {}
  // Aborts a plugin and removes it from the system.
  rpc AbortPlugin (AbortPluginRequest) returns (AbortPluginResponse) {}
  // Destroy the launcher.  If plugins are running it will attempt to stop them.  
  rpc Destroy (DestroyRequest) returns (DestroyResponse) {}
  // Ping the launcher.  
  rpc Ping (PingRequest) returns (PingResponse) {}
  // Discover plugins on the system that can be handled by this launcher.  
  rpc Discover (DiscoverRequest) returns (DiscoverResponse) {}
}

message LoadPluginRequest {
  string plugin_name = 1; //Assigned name for the plugin instance.  Must be unique in the system.  
  string path = 2; //Path to the plugin location on the system.
}

message LoadPluginResponse {
  cif.common.Status status = 1;
}

message AbortPluginRequest {
  string plugin_name = 1;
}

message AbortPluginResponse {
  cif.common.Status status = 1;
}

message DestroyRequest {}

message DestroyResponse {}

message PingRequest {}

message PingResponse {
  cif.management_common.LoaderInfoFull loader_info = 1;
}

message	DiscoverRequest {
  bool update_metadata = 1; //Updating the metadata can be time consuming.  
}

message	DiscoveredPlugin {
  string file_path = 1; //Fully qualified path needed for launcher
  string file_name = 2; //Name of the file on disk
  string plugin_type = 3; //Type of plugin
  cif.common.Version plugin_version = 4;
  cif.management_common.PluginMetadata plugin_metadata = 5;
  repeated string relative_path = 6; //Array of the relative path of the plugin in the plugin folder
}

message	DiscoverResponse {
  repeated DiscoveredPlugin discovered_plugins = 1;
  cif.common.Status status = 2;
}