syntax = "proto3";

import "cif_common.proto";

package cif.waveformmonitor;

service WaveformMonitor {
  rpc SetEnableWaveform (SetEnableWaveformRequest) returns (SetEnableWaveformResponse) {}
  rpc GetWaveform (GetWaveformRequest) returns (GetWaveformResponse) {}
}

message Waveforms {
   repeated Waveform waveforms = 1;
   bool valid = 2;
}

message Waveform {
   repeated double y = 1;
   int64 timestamp = 2;
   double dT = 3;
}

message SetEnableWaveformRequest {
   bool enable_waveform = 1;
}

message SetEnableWaveformResponse {
   cif.common.Status status = 1;
}

message GetWaveformRequest {}

message GetWaveformResponse {
   Waveforms waveforms = 1;
}