syntax = "proto3";

import "cif_common.proto";
import "cif_management_common.proto";

package cif.plugincore;

service PluginCore {
  rpc Start (StartRequest) returns (StartResponse) {}
  rpc Pause (PauseRequest) returns (PauseResponse) {}
  rpc Stop (StopRequest) returns (StopResponse) {}
  rpc RefreshStatistics (RefreshStatisticsRequest) returns (RefreshStatisticsResponse) {}
  rpc UpdateConfig (UpdateConfigRequest) returns (UpdateConfigResponse) {}
  rpc GetStatusData (GetStatusDataRequest) returns (GetStatusDataResponse) {}
  rpc GetVersion (GetVersionRequest) returns (GetVersionResponse) {}
  rpc GetConfig (GetConfigRequest) returns (GetConfigResponse) {}
  rpc GetOverrides (GetOverridesRequest) returns (GetOverridesResponse) {}
  rpc GetNames (GetNamesRequest) returns (GetNamesResponse) {}
}

message StartRequest {}

message StartResponse {
  cif.common.Status status = 1;
}

message PauseRequest {}

message PauseResponse {
  cif.common.Status status = 1;
}

message StopRequest {}

message StopResponse {
  cif.common.Status status = 1;
}

message RefreshStatisticsRequest {}

message RefreshStatisticsResponse {
  cif.common.Status status = 1;
}

message GetStatusDataRequest {}

message GetStatusDataResponse {
  cif.management_common.PluginStatusData status_data = 1;
}

message UpdateConfigRequest {
  Configuration configuration = 1;
}

message UpdateConfigResponse {
  cif.common.Status status = 1;
}

message GetVersionRequest {}

message GetVersionResponse {
  cif.common.Version version = 1;
}

message GetConfigRequest {}

message GetConfigResponse {
  Configuration configuration = 1;
}

message GetOverridesRequest {}

message GetOverridesResponse {
  PluginOverrides plugin_overrides = 1;
}

message GetNamesRequest {}

message GetNamesResponse {
  cif.common.PluginNames plugin_names = 1;
}

message Configuration {
  string json_config = 1;
}

message TimingOverrides {
   bool override_timing = 1;
   bool skip_sleep = 2;
   double period = 3;
}

message PluginOverrides {
   TimingOverrides timing_overrides = 1;
}