syntax = "proto3";

import "cif_common.proto";

package cif.filemonitor;

service FileMonitor {
  rpc GetBenchmarks (GetBenchmarksRequest) returns (GetBenchmarksResponse) {}
  rpc GetStatistics (GetStatisticsRequest) returns (GetStatisticsResponse) {}
  rpc GetLogManifest (GetLogManifestRequest) returns (GetLogManifestResponse) {}
  rpc GetDirectoryInfo (GetDirectoryInfoRequest) returns (GetDirectoryInfoResponse) {}
}

message FileStatistics {
   int32 file_count = 1;
   int32 rate_byte_sec = 2;
   int32 skipped_by_filter = 3;
   int32 read_written = 4;
   uint64 bytes = 5;
}

message FileBenchmark {
   int64 file_max = 1;
   double file_avg = 2;
   int64 file_min = 3;
   int64 flat_max = 4;
   double flat_avg = 5;
   int64 flat_min = 6;
}

message GetLogManifestResponse {
   LogManifestCore manifest_core = 1;
}

message LogManifestCore {
   string data_source_name = 1;
   string time_source = 2;
   string log_campaign_name = 3;
   int64 first_timestamp = 4;
}

message DirectoryInfo {
   repeated string files = 1;
   repeated string folders = 2;
}

message GetBenchmarksRequest {}

message GetBenchmarksResponse {
   FileBenchmark file_benchmark = 1;
}

message GetStatisticsRequest {}

message GetStatisticsResponse {
   FileStatistics file_statistics = 1;
}

message GetLogManifestRequest {}

message GetDirectoryInfoRequest {}

message GetDirectoryInfoResponse {
   DirectoryInfo directory_info = 1;
}