syntax = "proto3";

import "cif_common.proto";
//The CIF protos are installed in the default CIF data directory.  On Windows this is C:/Users/Public/Documents/CIF/protos
//When generating new gRPC server/client code this directory needs to be provided as an Import path

package cif.model_interface;

// This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

service ModelInterface {
   // List inport names for the loaded model  
   rpc GetInports (cif.common.Empty) returns (Channels) {}
   // List the outport names for the loaded model  
   rpc GetOutports (cif.common.Empty) returns (Channels) {}
   // Get the current state of the model  
   rpc GetModelState (cif.common.Empty) returns (ModelStateResponse) {}
   // List the exposed parameters for the loaded model  
   rpc GetParameters (cif.common.Empty) returns (Parameters) {}
   // Set a parameter value  
   rpc SetParameterValue (SetParameterRequest) returns (cif.common.Status) {}
   // Get a parameter value  
   rpc GetParameterValue (GetParameterRequest) returns (MonitoredData) {}
   // List the exposed signals for the loaded model  
   rpc GetSignals (cif.common.Empty) returns (GetSignalResponse) {}
   // Set the signals to monitor  
   rpc SetSignalList (Signals) returns (cif.common.Status) {}
   // Poll for the latest signal values  
   rpc MonitorSignals (cif.common.Empty) returns (MonitoredData) {}
   // List of models in the default directory  
   rpc ListModels (cif.common.Empty) returns (ModelList) {}
   // Get statistics for the plugin  
   rpc GetStatistics (cif.common.Empty) returns (Statistics) {}
}

message Statistics {
   uint64 iterations = 1;
   uint64 load_ctr = 2;
}

message ModelList {
    repeated string model_files = 1; //These are the models detected in the default location (/home/lvuser/models).
}

enum ModelState {
  NOT_LOADED = 0;
  UNINITIALIZED = 1;
  RUNNING = 2;
}

message ModelStateResponse {
  ModelState model_state = 1;
}

message Channels {
    repeated string channels = 1;
    cif.common.Status status = 2;
}

message ChannelRequest {
    repeated string channels = 1;
}

message Values {
    repeated double values = 1;
    cif.common.Status status = 2;
}

message Parameters {
    repeated Parameter parameters = 1;
    cif.common.Status status = 2;
}

message SetParameterRequest {
    string parameter_name = 1;
    repeated double parameter_value = 2;
}

message GetParameterRequest {
    string parameter_name = 1;
}

message MonitoredData {
    repeated double monitored_data = 1;
    cif.common.Status status = 2;
}

message GetSignalResponse {
    repeated Signal signals = 1;
    cif.common.Status status = 2;
}

message Signals {
    repeated string signal_names = 1;
}

message Signal {
    string name = 1; //name is format of blockname[signalname]
    uint32 dimension_1 = 2; //x dimension of a 2d vector.  A scalar will have dimension 1x1
    uint32 dimension_2 = 3; //y dimension 
    int32 port = 4;
}

message Parameter {
    string name = 1; //the path and name in the model of the parameter
    uint32 dimension_1 = 2; //x dimension of a 2d vector.  A scalar will have dimension 1x1
    uint32 dimension_2 = 3; //y dimension 
}


