syntax = "proto3";

import "cif_common.proto";

package cif.modbus_config;

service ModbusConfig {
  // Returns the current configuration of channels for Modbus
  rpc GetChannels (GetChannelsRequest) returns (GetChannelsResponse) {}
  // Returns a list of CSV files found in the default configuration directory
  rpc GetDirectoryInfo (GetDirectoryInfoRequest) returns (GetDirectoryInfoResponse) {}
  // Generates a configuration CSV file from channels
  rpc GenerateCSV (GenerateCSVRequest) returns (GenerateCSVResponse) {}
}

message GetChannelsRequest {}

message GetChannelsResponse {
   repeated ModbusChannel modbus_channels = 1;
}

message GenerateCSVRequest {
   repeated ModbusChannel modbus_channels = 1;
}

message GenerateCSVResponse {
  ModbusConfigCSV modbus_config_csv = 1;
}

message ModbusChannel {
   string channel_name = 1;
   uint32 start_address = 2;
   ModbusFunction modbus_function = 3;
   DataType data_type = 4;
   EndianWord endian_word = 5;
}

enum ModbusFunction {
  MODBUS_FUNCTION_UNKNOWN = 0;
  MODBUS_FUNCTION_READ_COIL = 1;
  MODBUS_FUNCTION_READ_HOLD_REG = 2;
  MODBUS_FUNCTION_READ_DI = 3;
  MODBUS_FUNCTION_READ_IN_REG = 4;
  MODBUS_FUNCTION_WRITE_COIL = 5;
  MODBUS_FUNCTION_WRITE_HOLD_REG = 6;
  MODBUS_FUNCTION_WRITE_DI = 7;
  MODBUS_FUNCTION_WRITE_IN_REG = 8;
}

enum DataType {
  DATATYPE_UNKNOWN = 0;
  DATATYPE_U16 = 1;
  DATATYPE_I16 = 2;
  DATATYPE_U32 = 3;
  DATATYPE_I32 = 4;
  DATATYPE_U64 = 5;
  DATATYPE_I64 = 6;
  DATATYPE_FLOAT32 = 7;
  DATATYPE_DOUBLE = 8;
}

enum EndianWord {
  ENDIAN_WORD_UNKNOWN = 0;
  ENDIAN_WORD_BIG = 1;
  ENDIAN_WORD_LITTLE = 2;
}

message ModbusConfigCSV {
   string modbus_config_csv = 1;
   cif.common.Status status = 2;
}

message GetDirectoryInfoRequest {}

message GetDirectoryInfoResponse {
   repeated string files = 1;
}