syntax = "proto3";

package cif.common;

message TimingStats {
  int64 max = 1;
  int64 min = 2;
  double avg = 3;
}

message Version {
  uint32 major = 1;
  uint32 minor = 2;
  uint32 fix = 3;
  uint32 build = 4;
}

message ShortVersion {
    uint32 major = 1;
    uint32 minor = 2;
    uint32 fix = 3;
  }

message PluginNames {
  string plugin_name = 1; //Assigned name for the plugin instance.  Unique in the system. 
  string plugin_type = 2; //Name of the plugin type
  string loader_name = 3; //Name of the loader for the plugin
}

message Status {
   int32 code = 1;
   string message = 2;
}

message Empty {}