# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cif_manager_pb2 as cif__manager__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cif_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadPlugin = channel.unary_unary(
                '/cif.manager.Manager/LoadPlugin',
                request_serializer=cif__manager__pb2.LoadPluginRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.LoadPluginResponse.FromString,
                _registered_method=True)
        self.RegisterPlugin = channel.unary_unary(
                '/cif.manager.Manager/RegisterPlugin',
                request_serializer=cif__manager__pb2.RegisterPluginRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.RegisterPluginResponse.FromString,
                _registered_method=True)
        self.UnregisterPlugin = channel.unary_unary(
                '/cif.manager.Manager/UnregisterPlugin',
                request_serializer=cif__manager__pb2.UnregisterPluginRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.UnregisterPluginResponse.FromString,
                _registered_method=True)
        self.QueryPluginTypes = channel.unary_unary(
                '/cif.manager.Manager/QueryPluginTypes',
                request_serializer=cif__manager__pb2.QueryPluginTypesRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryPluginTypesResponse.FromString,
                _registered_method=True)
        self.AbortPlugin = channel.unary_unary(
                '/cif.manager.Manager/AbortPlugin',
                request_serializer=cif__manager__pb2.AbortPluginRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.AbortPluginResponse.FromString,
                _registered_method=True)
        self.UnloadAllPlugins = channel.unary_unary(
                '/cif.manager.Manager/UnloadAllPlugins',
                request_serializer=cif__manager__pb2.AbortAllPluginsRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.AbortAllPluginsResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/cif.manager.Manager/Destroy',
                request_serializer=cif__manager__pb2.DestroyRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.DestroyResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/cif.manager.Manager/Ping',
                request_serializer=cif__manager__pb2.PingRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.PingResponse.FromString,
                _registered_method=True)
        self.QueryErrors = channel.unary_unary(
                '/cif.manager.Manager/QueryErrors',
                request_serializer=cif__manager__pb2.QueryErrorsRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryErrorsResponse.FromString,
                _registered_method=True)
        self.QueryConfig = channel.unary_unary(
                '/cif.manager.Manager/QueryConfig',
                request_serializer=cif__manager__pb2.QueryConfigRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryConfigResponse.FromString,
                _registered_method=True)
        self.QueryInfo = channel.unary_unary(
                '/cif.manager.Manager/QueryInfo',
                request_serializer=cif__manager__pb2.QueryInfoRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryInfoResponse.FromString,
                _registered_method=True)
        self.ResetErrorIndex = channel.unary_unary(
                '/cif.manager.Manager/ResetErrorIndex',
                request_serializer=cif__manager__pb2.ResetErrorIndexRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.ResetErrorIndexResponse.FromString,
                _registered_method=True)
        self.ResetConfigIndex = channel.unary_unary(
                '/cif.manager.Manager/ResetConfigIndex',
                request_serializer=cif__manager__pb2.ResetConfigIndexRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.ResetConfigIndexResponse.FromString,
                _registered_method=True)
        self.ResetInfoIndex = channel.unary_unary(
                '/cif.manager.Manager/ResetInfoIndex',
                request_serializer=cif__manager__pb2.ResetInfoIndexRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.ResetInfoIndexResponse.FromString,
                _registered_method=True)
        self.QueryPluginInfo = channel.unary_unary(
                '/cif.manager.Manager/QueryPluginInfo',
                request_serializer=cif__manager__pb2.QueryPluginInfoRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryPluginInfoResponse.FromString,
                _registered_method=True)
        self.QueryPlugin = channel.unary_unary(
                '/cif.manager.Manager/QueryPlugin',
                request_serializer=cif__manager__pb2.QueryPluginRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryPluginResponse.FromString,
                _registered_method=True)
        self.QuerySystemStatus = channel.unary_unary(
                '/cif.manager.Manager/QuerySystemStatus',
                request_serializer=cif__manager__pb2.QuerySystemStatusRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QuerySystemStatusResponse.FromString,
                _registered_method=True)
        self.UpdateClock = channel.unary_unary(
                '/cif.manager.Manager/UpdateClock',
                request_serializer=cif__manager__pb2.UpdateClockRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.UpdateClockResponse.FromString,
                _registered_method=True)
        self.CreateOrch = channel.unary_unary(
                '/cif.manager.Manager/CreateOrch',
                request_serializer=cif__manager__pb2.CreateOrchRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.CreateOrchResponse.FromString,
                _registered_method=True)
        self.QueryClockStatus = channel.unary_unary(
                '/cif.manager.Manager/QueryClockStatus',
                request_serializer=cif__manager__pb2.QueryClockStatusRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryClockStatusResponse.FromString,
                _registered_method=True)
        self.QueryAllChannels = channel.unary_unary(
                '/cif.manager.Manager/QueryAllChannels',
                request_serializer=cif__manager__pb2.QueryAllChannelsRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryAllChannelsResponse.FromString,
                _registered_method=True)
        self.RegisterPluginLoader = channel.unary_unary(
                '/cif.manager.Manager/RegisterPluginLoader',
                request_serializer=cif__manager__pb2.RegisterPluginLoaderRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.RegisterPluginLoaderResponse.FromString,
                _registered_method=True)
        self.UnregisterPluginLoader = channel.unary_unary(
                '/cif.manager.Manager/UnregisterPluginLoader',
                request_serializer=cif__manager__pb2.UnregisterPluginLoaderRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.UnregisterPluginLoaderResponse.FromString,
                _registered_method=True)
        self.CreatePluginLoader = channel.unary_unary(
                '/cif.manager.Manager/CreatePluginLoader',
                request_serializer=cif__manager__pb2.CreatePluginLoaderRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.CreatePluginLoaderResponse.FromString,
                _registered_method=True)
        self.DestroyPluginLoader = channel.unary_unary(
                '/cif.manager.Manager/DestroyPluginLoader',
                request_serializer=cif__manager__pb2.DestroyPluginLoaderRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.DestroyPluginLoaderResponse.FromString,
                _registered_method=True)
        self.QueryPluginLoaders = channel.unary_unary(
                '/cif.manager.Manager/QueryPluginLoaders',
                request_serializer=cif__manager__pb2.QueryPluginLoadersRequest.SerializeToString,
                response_deserializer=cif__manager__pb2.QueryPluginLoadersResponse.FromString,
                _registered_method=True)


class ManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadPlugin(self, request, context):
        """Load a specific plugin instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPlugin(self, request, context):
        """Plugin calls this to register itself with the manager.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterPlugin(self, request, context):
        """Plugin calls this to unregister itself with the manager.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPluginTypes(self, request, context):
        """Gets the names of all Plugin Types on the system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortPlugin(self, request, context):
        """Aborts a plugin.  This should only be used if a plug-in is not responding to normal commands.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadAllPlugins(self, request, context):
        """Unload all the instantiated plugins. If the plugins are running it will attempt to stop them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Destroy the manager.  If plugins are running it will attempt to stop them.  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping the manager.  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryErrors(self, request, context):
        """Query the errors occurred.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryConfig(self, request, context):
        """Query the config from the log.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryInfo(self, request, context):
        """Query the info from the log.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetErrorIndex(self, request, context):
        """Reset the filter time for returned errors. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetConfigIndex(self, request, context):
        """Reset the filter time for returned configuration. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetInfoIndex(self, request, context):
        """Reset the filter time for returned information. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPluginInfo(self, request, context):
        """Gets the name, type, status, and gRPC port of all loaded plugins.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPlugin(self, request, context):
        """Gets the name, type, status, and gRPC port of loaded plugin by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySystemStatus(self, request, context):
        """Provides the plugin status and requests system status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClock(self, request, context):
        """Updates a tracked clock with a new timestamp pair or a reset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrch(self, request, context):
        """Create orchestration file from logged configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryClockStatus(self, request, context):
        """Query the errors occurred.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAllChannels(self, request, context):
        """Query all channels on the system matching the filter.  Filter parameters are AND to pass.  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPluginLoader(self, request, context):
        """The loader calls this to register itself with the manager.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterPluginLoader(self, request, context):
        """The loader calls this to unregister itself with the manager.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePluginLoader(self, request, context):
        """Manually create a new plugin loader.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyPluginLoader(self, request, context):
        """Manually destroy an existing plugin loader.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPluginLoaders(self, request, context):
        """Gets the name, type, PID, and gRPC port of all registered plugin loaders.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPlugin,
                    request_deserializer=cif__manager__pb2.LoadPluginRequest.FromString,
                    response_serializer=cif__manager__pb2.LoadPluginResponse.SerializeToString,
            ),
            'RegisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlugin,
                    request_deserializer=cif__manager__pb2.RegisterPluginRequest.FromString,
                    response_serializer=cif__manager__pb2.RegisterPluginResponse.SerializeToString,
            ),
            'UnregisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterPlugin,
                    request_deserializer=cif__manager__pb2.UnregisterPluginRequest.FromString,
                    response_serializer=cif__manager__pb2.UnregisterPluginResponse.SerializeToString,
            ),
            'QueryPluginTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPluginTypes,
                    request_deserializer=cif__manager__pb2.QueryPluginTypesRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryPluginTypesResponse.SerializeToString,
            ),
            'AbortPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortPlugin,
                    request_deserializer=cif__manager__pb2.AbortPluginRequest.FromString,
                    response_serializer=cif__manager__pb2.AbortPluginResponse.SerializeToString,
            ),
            'UnloadAllPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadAllPlugins,
                    request_deserializer=cif__manager__pb2.AbortAllPluginsRequest.FromString,
                    response_serializer=cif__manager__pb2.AbortAllPluginsResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=cif__manager__pb2.DestroyRequest.FromString,
                    response_serializer=cif__manager__pb2.DestroyResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=cif__manager__pb2.PingRequest.FromString,
                    response_serializer=cif__manager__pb2.PingResponse.SerializeToString,
            ),
            'QueryErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryErrors,
                    request_deserializer=cif__manager__pb2.QueryErrorsRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryErrorsResponse.SerializeToString,
            ),
            'QueryConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryConfig,
                    request_deserializer=cif__manager__pb2.QueryConfigRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryConfigResponse.SerializeToString,
            ),
            'QueryInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryInfo,
                    request_deserializer=cif__manager__pb2.QueryInfoRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryInfoResponse.SerializeToString,
            ),
            'ResetErrorIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetErrorIndex,
                    request_deserializer=cif__manager__pb2.ResetErrorIndexRequest.FromString,
                    response_serializer=cif__manager__pb2.ResetErrorIndexResponse.SerializeToString,
            ),
            'ResetConfigIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetConfigIndex,
                    request_deserializer=cif__manager__pb2.ResetConfigIndexRequest.FromString,
                    response_serializer=cif__manager__pb2.ResetConfigIndexResponse.SerializeToString,
            ),
            'ResetInfoIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetInfoIndex,
                    request_deserializer=cif__manager__pb2.ResetInfoIndexRequest.FromString,
                    response_serializer=cif__manager__pb2.ResetInfoIndexResponse.SerializeToString,
            ),
            'QueryPluginInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPluginInfo,
                    request_deserializer=cif__manager__pb2.QueryPluginInfoRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryPluginInfoResponse.SerializeToString,
            ),
            'QueryPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPlugin,
                    request_deserializer=cif__manager__pb2.QueryPluginRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryPluginResponse.SerializeToString,
            ),
            'QuerySystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySystemStatus,
                    request_deserializer=cif__manager__pb2.QuerySystemStatusRequest.FromString,
                    response_serializer=cif__manager__pb2.QuerySystemStatusResponse.SerializeToString,
            ),
            'UpdateClock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClock,
                    request_deserializer=cif__manager__pb2.UpdateClockRequest.FromString,
                    response_serializer=cif__manager__pb2.UpdateClockResponse.SerializeToString,
            ),
            'CreateOrch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrch,
                    request_deserializer=cif__manager__pb2.CreateOrchRequest.FromString,
                    response_serializer=cif__manager__pb2.CreateOrchResponse.SerializeToString,
            ),
            'QueryClockStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryClockStatus,
                    request_deserializer=cif__manager__pb2.QueryClockStatusRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryClockStatusResponse.SerializeToString,
            ),
            'QueryAllChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAllChannels,
                    request_deserializer=cif__manager__pb2.QueryAllChannelsRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryAllChannelsResponse.SerializeToString,
            ),
            'RegisterPluginLoader': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPluginLoader,
                    request_deserializer=cif__manager__pb2.RegisterPluginLoaderRequest.FromString,
                    response_serializer=cif__manager__pb2.RegisterPluginLoaderResponse.SerializeToString,
            ),
            'UnregisterPluginLoader': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterPluginLoader,
                    request_deserializer=cif__manager__pb2.UnregisterPluginLoaderRequest.FromString,
                    response_serializer=cif__manager__pb2.UnregisterPluginLoaderResponse.SerializeToString,
            ),
            'CreatePluginLoader': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePluginLoader,
                    request_deserializer=cif__manager__pb2.CreatePluginLoaderRequest.FromString,
                    response_serializer=cif__manager__pb2.CreatePluginLoaderResponse.SerializeToString,
            ),
            'DestroyPluginLoader': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyPluginLoader,
                    request_deserializer=cif__manager__pb2.DestroyPluginLoaderRequest.FromString,
                    response_serializer=cif__manager__pb2.DestroyPluginLoaderResponse.SerializeToString,
            ),
            'QueryPluginLoaders': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPluginLoaders,
                    request_deserializer=cif__manager__pb2.QueryPluginLoadersRequest.FromString,
                    response_serializer=cif__manager__pb2.QueryPluginLoadersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cif.manager.Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cif.manager.Manager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Manager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/LoadPlugin',
            cif__manager__pb2.LoadPluginRequest.SerializeToString,
            cif__manager__pb2.LoadPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/RegisterPlugin',
            cif__manager__pb2.RegisterPluginRequest.SerializeToString,
            cif__manager__pb2.RegisterPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/UnregisterPlugin',
            cif__manager__pb2.UnregisterPluginRequest.SerializeToString,
            cif__manager__pb2.UnregisterPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPluginTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryPluginTypes',
            cif__manager__pb2.QueryPluginTypesRequest.SerializeToString,
            cif__manager__pb2.QueryPluginTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/AbortPlugin',
            cif__manager__pb2.AbortPluginRequest.SerializeToString,
            cif__manager__pb2.AbortPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadAllPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/UnloadAllPlugins',
            cif__manager__pb2.AbortAllPluginsRequest.SerializeToString,
            cif__manager__pb2.AbortAllPluginsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/Destroy',
            cif__manager__pb2.DestroyRequest.SerializeToString,
            cif__manager__pb2.DestroyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/Ping',
            cif__manager__pb2.PingRequest.SerializeToString,
            cif__manager__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryErrors',
            cif__manager__pb2.QueryErrorsRequest.SerializeToString,
            cif__manager__pb2.QueryErrorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryConfig',
            cif__manager__pb2.QueryConfigRequest.SerializeToString,
            cif__manager__pb2.QueryConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryInfo',
            cif__manager__pb2.QueryInfoRequest.SerializeToString,
            cif__manager__pb2.QueryInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetErrorIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/ResetErrorIndex',
            cif__manager__pb2.ResetErrorIndexRequest.SerializeToString,
            cif__manager__pb2.ResetErrorIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetConfigIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/ResetConfigIndex',
            cif__manager__pb2.ResetConfigIndexRequest.SerializeToString,
            cif__manager__pb2.ResetConfigIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetInfoIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/ResetInfoIndex',
            cif__manager__pb2.ResetInfoIndexRequest.SerializeToString,
            cif__manager__pb2.ResetInfoIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPluginInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryPluginInfo',
            cif__manager__pb2.QueryPluginInfoRequest.SerializeToString,
            cif__manager__pb2.QueryPluginInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryPlugin',
            cif__manager__pb2.QueryPluginRequest.SerializeToString,
            cif__manager__pb2.QueryPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QuerySystemStatus',
            cif__manager__pb2.QuerySystemStatusRequest.SerializeToString,
            cif__manager__pb2.QuerySystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/UpdateClock',
            cif__manager__pb2.UpdateClockRequest.SerializeToString,
            cif__manager__pb2.UpdateClockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/CreateOrch',
            cif__manager__pb2.CreateOrchRequest.SerializeToString,
            cif__manager__pb2.CreateOrchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryClockStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryClockStatus',
            cif__manager__pb2.QueryClockStatusRequest.SerializeToString,
            cif__manager__pb2.QueryClockStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAllChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryAllChannels',
            cif__manager__pb2.QueryAllChannelsRequest.SerializeToString,
            cif__manager__pb2.QueryAllChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPluginLoader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/RegisterPluginLoader',
            cif__manager__pb2.RegisterPluginLoaderRequest.SerializeToString,
            cif__manager__pb2.RegisterPluginLoaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterPluginLoader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/UnregisterPluginLoader',
            cif__manager__pb2.UnregisterPluginLoaderRequest.SerializeToString,
            cif__manager__pb2.UnregisterPluginLoaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePluginLoader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/CreatePluginLoader',
            cif__manager__pb2.CreatePluginLoaderRequest.SerializeToString,
            cif__manager__pb2.CreatePluginLoaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyPluginLoader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/DestroyPluginLoader',
            cif__manager__pb2.DestroyPluginLoaderRequest.SerializeToString,
            cif__manager__pb2.DestroyPluginLoaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPluginLoaders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryPluginLoaders',
            cif__manager__pb2.QueryPluginLoadersRequest.SerializeToString,
            cif__manager__pb2.QueryPluginLoadersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
