# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cif_channel_core_pb2 as cif__channel__core__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cif_channel_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChannelCoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChannels = channel.unary_unary(
                '/cif.channelcore.ChannelCore/GetChannels',
                request_serializer=cif__channel__core__pb2.GetChannelsRequest.SerializeToString,
                response_deserializer=cif__channel__core__pb2.GetChannelsResponse.FromString,
                _registered_method=True)
        self.SetConnection = channel.unary_unary(
                '/cif.channelcore.ChannelCore/SetConnection',
                request_serializer=cif__channel__core__pb2.SetConnectionRequest.SerializeToString,
                response_deserializer=cif__channel__core__pb2.SetConnectionResponse.FromString,
                _registered_method=True)
        self.SetForce = channel.unary_unary(
                '/cif.channelcore.ChannelCore/SetForce',
                request_serializer=cif__channel__core__pb2.SetForceRequest.SerializeToString,
                response_deserializer=cif__channel__core__pb2.SetForceResponse.FromString,
                _registered_method=True)
        self.CreateFIFOInstance = channel.unary_unary(
                '/cif.channelcore.ChannelCore/CreateFIFOInstance',
                request_serializer=cif__channel__core__pb2.CreateFIFOInstanceRequest.SerializeToString,
                response_deserializer=cif__channel__core__pb2.CreateFIFOInstanceResponse.FromString,
                _registered_method=True)
        self.DestroyFIFOInstance = channel.unary_unary(
                '/cif.channelcore.ChannelCore/DestroyFIFOInstance',
                request_serializer=cif__channel__core__pb2.DestroyFIFOInstanceRequest.SerializeToString,
                response_deserializer=cif__channel__core__pb2.DestroyFIFOInstanceResponse.FromString,
                _registered_method=True)


class ChannelCoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChannels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetForce(self, request, context):
        """This is only supported on tags.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFIFOInstance(self, request, context):
        """This is needed when the publisher needs to provide information to support a subscriber.  For instance if a new publisher needs to be
        created for a 1-1 FIFO or if backpressure is used and the publisher needs to provide the handles.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyFIFOInstance(self, request, context):
        """This is used to destroy or disconnect a subscriber after the CreateFIFOInstance was used.  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChannelCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannels,
                    request_deserializer=cif__channel__core__pb2.GetChannelsRequest.FromString,
                    response_serializer=cif__channel__core__pb2.GetChannelsResponse.SerializeToString,
            ),
            'SetConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConnection,
                    request_deserializer=cif__channel__core__pb2.SetConnectionRequest.FromString,
                    response_serializer=cif__channel__core__pb2.SetConnectionResponse.SerializeToString,
            ),
            'SetForce': grpc.unary_unary_rpc_method_handler(
                    servicer.SetForce,
                    request_deserializer=cif__channel__core__pb2.SetForceRequest.FromString,
                    response_serializer=cif__channel__core__pb2.SetForceResponse.SerializeToString,
            ),
            'CreateFIFOInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFIFOInstance,
                    request_deserializer=cif__channel__core__pb2.CreateFIFOInstanceRequest.FromString,
                    response_serializer=cif__channel__core__pb2.CreateFIFOInstanceResponse.SerializeToString,
            ),
            'DestroyFIFOInstance': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyFIFOInstance,
                    request_deserializer=cif__channel__core__pb2.DestroyFIFOInstanceRequest.FromString,
                    response_serializer=cif__channel__core__pb2.DestroyFIFOInstanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cif.channelcore.ChannelCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cif.channelcore.ChannelCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChannelCore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.channelcore.ChannelCore/GetChannels',
            cif__channel__core__pb2.GetChannelsRequest.SerializeToString,
            cif__channel__core__pb2.GetChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.channelcore.ChannelCore/SetConnection',
            cif__channel__core__pb2.SetConnectionRequest.SerializeToString,
            cif__channel__core__pb2.SetConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetForce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.channelcore.ChannelCore/SetForce',
            cif__channel__core__pb2.SetForceRequest.SerializeToString,
            cif__channel__core__pb2.SetForceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFIFOInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.channelcore.ChannelCore/CreateFIFOInstance',
            cif__channel__core__pb2.CreateFIFOInstanceRequest.SerializeToString,
            cif__channel__core__pb2.CreateFIFOInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyFIFOInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.channelcore.ChannelCore/DestroyFIFOInstance',
            cif__channel__core__pb2.DestroyFIFOInstanceRequest.SerializeToString,
            cif__channel__core__pb2.DestroyFIFOInstanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
