# This file should be installed on RT target at /home/lvuser/CIF
# This file should be installed on Windows target at C:\Users\Public\Documents\CIF Data

[Security]
# You can follow the link below to generate SSL certificates.
# https://github.com/ni/grpc-labview/blob/master/docs/Certificates.md

#   Script to generate certificate with openssl
#       mypass="password123"
#
#       echo Generate server key:
#       openssl genrsa -passout pass:$mypass -des3 -out server.key 4096
#
#       echo Generate server signing request:
#       openssl req -passin pass:$mypass -new -key server.key -out server.csr -subj  "/C=US/ST=TX/L=Austin/O=NI/OU=labview/CN=localhost"
#
#       echo Self-sign server certificate:
#       openssl x509 -req -passin pass:$mypass -days 365 -in server.csr -signkey server.key -set_serial 01 -out server.crt
#
#       echo Remove passphrase from server key:
#       openssl rsa -passin pass:$mypass -in server.key -out server.key
#
#       rm server.csr

# e.g. Assign the server private key path as below
# Server_Private_Key_File=/home/lvuser/CIF/server.key
Server_Private_Key_File=

# e.g. Assign the server certificate path as below
# Server_Certificate_File=/home/lvuser/CIF/server.crt
Server_Certificate_File=

# If SSL cert is configured, the default value "0.0.0.0" cannot be used as domain name.
# Specify the valid domain name which matches the common name (CN) in server.crt
# You can use `openssl x509 -noout -subject -nameopt multiline -in server.crt | grep commonName`
# to query the common name from server.crt
# Domain_Name=NI-PXIe-8880-xxxx
Domain_Name=0.0.0.0

# Set the gRPC port for the manager application.  The default is 15882.  Changing this may cause clients to not be able to connect.
Manager_Port=15882