#For Ubuntu CIF Log configuration file for rsyslog config
#This needs to be placed in /etc/rsyslog.d/
#To test and debug calling rsyslogd -N1 will check syntax
#Calling <sudo systemctl restart rsyslog> will reload with the new configuration
#Calling <logger -p local5.info -t cif "Test message"> will create a log in the cif_info.log
#Apparmor also needs to be configured to allow rsyslog rw access to /var/local/cif/logs/

global(parser.escapeControlCharacterTab="off")

# 1. Define the custom CIF log template
template(name="ciflog" type="string" 
    string="%timereported:::date-month%/%timereported:::date-day%/%timereported:::date-year% %timereported:::date-hour%:%timereported:::date-minute%:%timereported:::date-second%\t%msg:2:$%\n"
)

# 2. Process Local5 messages with "cif" in the header
if ($syslogfacility-text == 'local5' and $syslogtag contains 'cif') then {

    # Error Level Filter
    if ($syslogpriority-text == 'err') then {
        action(type="omfile" 
               file="/var/local/cif/logs/cif_error.log" 
               template="ciflog"
               fileCreateMode="0666")
    }

    # Notice Level Filter (Config)
    else if ($syslogpriority-text == 'notice') then {
        action(type="omfile" 
               file="/var/local/cif/logs/cif_config.log" 
               template="ciflog"
               fileCreateMode="0666")
    }

    # Info Level Filter
    else if ($syslogpriority-text == 'info') then {
        action(type="omfile" 
               file="/var/local/cif/logs/cif_info.log" 
               template="ciflog"
               fileCreateMode="0666")
    }

    stop
}
