# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cif_tag_monitor_plugin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cif_tag_monitor_plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import cif_common_pb2 as cif__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63if_tag_monitor_plugin.proto\x12\x0f\x63if.tag_monitor\x1a\x10\x63if_common.proto\"\x1f\n\x0fTagValueRequest\x12\x0c\n\x04tags\x18\x01 \x03(\t\"P\n\x16\x44oubleTagValueResponse\x12\x12\n\ntag_values\x18\x01 \x03(\x01\x12\"\n\x06status\x18\x02 \x01(\x0b\x32\x12.cif.common.Status2o\n\nTagMonitor\x12\x61\n\x12GetDoubleTagValues\x12 .cif.tag_monitor.TagValueRequest\x1a\'.cif.tag_monitor.DoubleTagValueResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cif_tag_monitor_plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAGVALUEREQUEST']._serialized_start=67
  _globals['_TAGVALUEREQUEST']._serialized_end=98
  _globals['_DOUBLETAGVALUERESPONSE']._serialized_start=100
  _globals['_DOUBLETAGVALUERESPONSE']._serialized_end=180
  _globals['_TAGMONITOR']._serialized_start=182
  _globals['_TAGMONITOR']._serialized_end=293
# @@protoc_insertion_point(module_scope)
