# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cif_channel_core_pb2 as cif__channel__core__pb2
import cif_common_pb2 as cif__common__pb2
import cif_manager_pb2 as cif__manager__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cif_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadPlugin = channel.unary_unary(
                '/cif.manager.Manager/LoadPlugin',
                request_serializer=cif__manager__pb2.PluginConfig.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.RegisterPlugin = channel.unary_unary(
                '/cif.manager.Manager/RegisterPlugin',
                request_serializer=cif__manager__pb2.RegisterData.SerializeToString,
                response_deserializer=cif__common__pb2.Empty.FromString,
                _registered_method=True)
        self.UnregisterPlugin = channel.unary_unary(
                '/cif.manager.Manager/UnregisterPlugin',
                request_serializer=cif__manager__pb2.UnregisterData.SerializeToString,
                response_deserializer=cif__common__pb2.Empty.FromString,
                _registered_method=True)
        self.QueryPluginTypes = channel.unary_unary(
                '/cif.manager.Manager/QueryPluginTypes',
                request_serializer=cif__manager__pb2.QueryTypeSettings.SerializeToString,
                response_deserializer=cif__manager__pb2.PluginTypeReply.FromString,
                _registered_method=True)
        self.AbortPlugin = channel.unary_unary(
                '/cif.manager.Manager/AbortPlugin',
                request_serializer=cif__manager__pb2.PluginName.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.UnloadAllPlugins = channel.unary_unary(
                '/cif.manager.Manager/UnloadAllPlugins',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/cif.manager.Manager/Destroy',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Empty.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/cif.manager.Manager/Ping',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.QueryErrors = channel.unary_unary(
                '/cif.manager.Manager/QueryErrors',
                request_serializer=cif__manager__pb2.QuerySettings.SerializeToString,
                response_deserializer=cif__manager__pb2.ErrorInfoList.FromString,
                _registered_method=True)
        self.QueryConfig = channel.unary_unary(
                '/cif.manager.Manager/QueryConfig',
                request_serializer=cif__manager__pb2.QuerySettings.SerializeToString,
                response_deserializer=cif__manager__pb2.FileData.FromString,
                _registered_method=True)
        self.QueryInfo = channel.unary_unary(
                '/cif.manager.Manager/QueryInfo',
                request_serializer=cif__manager__pb2.QuerySettings.SerializeToString,
                response_deserializer=cif__manager__pb2.FileData.FromString,
                _registered_method=True)
        self.ResetErrorIndex = channel.unary_unary(
                '/cif.manager.Manager/ResetErrorIndex',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.ResetConfigIndex = channel.unary_unary(
                '/cif.manager.Manager/ResetConfigIndex',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.ResetInfoIndex = channel.unary_unary(
                '/cif.manager.Manager/ResetInfoIndex',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.QueryPluginInfo = channel.unary_unary(
                '/cif.manager.Manager/QueryPluginInfo',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__manager__pb2.PluginInfoArray.FromString,
                _registered_method=True)
        self.QueryPlugin = channel.unary_unary(
                '/cif.manager.Manager/QueryPlugin',
                request_serializer=cif__manager__pb2.PluginName.SerializeToString,
                response_deserializer=cif__manager__pb2.PluginInfoResponse.FromString,
                _registered_method=True)
        self.QuerySystemStatus = channel.unary_unary(
                '/cif.manager.Manager/QuerySystemStatus',
                request_serializer=cif__manager__pb2.PluginStatus.SerializeToString,
                response_deserializer=cif__manager__pb2.SystemStatus.FromString,
                _registered_method=True)
        self.UpdateClock = channel.unary_unary(
                '/cif.manager.Manager/UpdateClock',
                request_serializer=cif__manager__pb2.ClockUpdate.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.CreateOrch = channel.unary_unary(
                '/cif.manager.Manager/CreateOrch',
                request_serializer=cif__manager__pb2.OrchConfig.SerializeToString,
                response_deserializer=cif__manager__pb2.OrchReturn.FromString,
                _registered_method=True)
        self.QueryClockStatus = channel.unary_unary(
                '/cif.manager.Manager/QueryClockStatus',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__manager__pb2.ClockStatusArray.FromString,
                _registered_method=True)
        self.QueryAllChannels = channel.unary_unary(
                '/cif.manager.Manager/QueryAllChannels',
                request_serializer=cif__channel__core__pb2.ChannelFilter.SerializeToString,
                response_deserializer=cif__channel__core__pb2.Channels.FromString,
                _registered_method=True)


class ManagerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadPlugin(self, request, context):
        """Load a specific plugin instance.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPlugin(self, request, context):
        """Plugin calls this to register itself with the manager.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterPlugin(self, request, context):
        """Plugin calls this to unregister itself with the manager.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPluginTypes(self, request, context):
        """Gets the names of all Plugin Types on the system.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortPlugin(self, request, context):
        """Aborts a plugin.  This should only be used if a plug-in is not responding to normal commands.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadAllPlugins(self, request, context):
        """Unload all the instantiated plugins. If the plugins are running it will attempt to stop them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Destroy the manager.  If plugins are running it will attempt to stop them.  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping the manager.  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryErrors(self, request, context):
        """Query the errors occurred.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryConfig(self, request, context):
        """Query the errors occurred.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryInfo(self, request, context):
        """Query the errors occurred.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetErrorIndex(self, request, context):
        """Reset the filter time for returned errors. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetConfigIndex(self, request, context):
        """Reset the filter time for returned configuration. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetInfoIndex(self, request, context):
        """Reset the filter time for returned information. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPluginInfo(self, request, context):
        """Gets the name, type, status, and gRPC port of all loaded plugins.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryPlugin(self, request, context):
        """Gets the name, type, status, and gRPC port of loaded plugin by name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySystemStatus(self, request, context):
        """Provides the plugin status and requests system status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateClock(self, request, context):
        """Updates a tracked clock with a new timestamp pair or a reset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateOrch(self, request, context):
        """Create orchestration file from logged configuration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryClockStatus(self, request, context):
        """Query the errors occurred.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryAllChannels(self, request, context):
        """Query all channels on the system matching the filter.  Filter parameters are AND to pass.  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadPlugin,
                    request_deserializer=cif__manager__pb2.PluginConfig.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'RegisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlugin,
                    request_deserializer=cif__manager__pb2.RegisterData.FromString,
                    response_serializer=cif__common__pb2.Empty.SerializeToString,
            ),
            'UnregisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterPlugin,
                    request_deserializer=cif__manager__pb2.UnregisterData.FromString,
                    response_serializer=cif__common__pb2.Empty.SerializeToString,
            ),
            'QueryPluginTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPluginTypes,
                    request_deserializer=cif__manager__pb2.QueryTypeSettings.FromString,
                    response_serializer=cif__manager__pb2.PluginTypeReply.SerializeToString,
            ),
            'AbortPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortPlugin,
                    request_deserializer=cif__manager__pb2.PluginName.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'UnloadAllPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadAllPlugins,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Empty.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'QueryErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryErrors,
                    request_deserializer=cif__manager__pb2.QuerySettings.FromString,
                    response_serializer=cif__manager__pb2.ErrorInfoList.SerializeToString,
            ),
            'QueryConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryConfig,
                    request_deserializer=cif__manager__pb2.QuerySettings.FromString,
                    response_serializer=cif__manager__pb2.FileData.SerializeToString,
            ),
            'QueryInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryInfo,
                    request_deserializer=cif__manager__pb2.QuerySettings.FromString,
                    response_serializer=cif__manager__pb2.FileData.SerializeToString,
            ),
            'ResetErrorIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetErrorIndex,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'ResetConfigIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetConfigIndex,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'ResetInfoIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetInfoIndex,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'QueryPluginInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPluginInfo,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__manager__pb2.PluginInfoArray.SerializeToString,
            ),
            'QueryPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryPlugin,
                    request_deserializer=cif__manager__pb2.PluginName.FromString,
                    response_serializer=cif__manager__pb2.PluginInfoResponse.SerializeToString,
            ),
            'QuerySystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySystemStatus,
                    request_deserializer=cif__manager__pb2.PluginStatus.FromString,
                    response_serializer=cif__manager__pb2.SystemStatus.SerializeToString,
            ),
            'UpdateClock': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateClock,
                    request_deserializer=cif__manager__pb2.ClockUpdate.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'CreateOrch': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateOrch,
                    request_deserializer=cif__manager__pb2.OrchConfig.FromString,
                    response_serializer=cif__manager__pb2.OrchReturn.SerializeToString,
            ),
            'QueryClockStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryClockStatus,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__manager__pb2.ClockStatusArray.SerializeToString,
            ),
            'QueryAllChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryAllChannels,
                    request_deserializer=cif__channel__core__pb2.ChannelFilter.FromString,
                    response_serializer=cif__channel__core__pb2.Channels.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cif.manager.Manager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cif.manager.Manager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Manager(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/LoadPlugin',
            cif__manager__pb2.PluginConfig.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/RegisterPlugin',
            cif__manager__pb2.RegisterData.SerializeToString,
            cif__common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/UnregisterPlugin',
            cif__manager__pb2.UnregisterData.SerializeToString,
            cif__common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPluginTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryPluginTypes',
            cif__manager__pb2.QueryTypeSettings.SerializeToString,
            cif__manager__pb2.PluginTypeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/AbortPlugin',
            cif__manager__pb2.PluginName.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadAllPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/UnloadAllPlugins',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/Destroy',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/Ping',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryErrors',
            cif__manager__pb2.QuerySettings.SerializeToString,
            cif__manager__pb2.ErrorInfoList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryConfig',
            cif__manager__pb2.QuerySettings.SerializeToString,
            cif__manager__pb2.FileData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryInfo',
            cif__manager__pb2.QuerySettings.SerializeToString,
            cif__manager__pb2.FileData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetErrorIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/ResetErrorIndex',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetConfigIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/ResetConfigIndex',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetInfoIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/ResetInfoIndex',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPluginInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryPluginInfo',
            cif__common__pb2.Empty.SerializeToString,
            cif__manager__pb2.PluginInfoArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryPlugin',
            cif__manager__pb2.PluginName.SerializeToString,
            cif__manager__pb2.PluginInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QuerySystemStatus',
            cif__manager__pb2.PluginStatus.SerializeToString,
            cif__manager__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateClock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/UpdateClock',
            cif__manager__pb2.ClockUpdate.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateOrch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/CreateOrch',
            cif__manager__pb2.OrchConfig.SerializeToString,
            cif__manager__pb2.OrchReturn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryClockStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryClockStatus',
            cif__common__pb2.Empty.SerializeToString,
            cif__manager__pb2.ClockStatusArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryAllChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.manager.Manager/QueryAllChannels',
            cif__channel__core__pb2.ChannelFilter.SerializeToString,
            cif__channel__core__pb2.Channels.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
