[cif_startup_linux.exe]
server.app.propertiesEnabled=True
server.tcp.serviceName="My Computer/VI Server"
server.vi.propertiesEnabled=True
WebServer.TcpAccess="c+*"
WebServer.ViAccess="+*"
DebugServerEnabled=False
DebugServerWaitOnLaunch=False
xwmShellRect.NoTitle=0x0+0+0
xwmShellRect.Title=14x17+14+49
