# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cif_common_pb2 as cif__common__pb2
import cif_model_interface_plugin_pb2 as cif__model__interface__plugin__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cif_model_interface_plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelInterfaceStub(object):
    """This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInports = channel.unary_unary(
                '/cif.model_interface.ModelInterface/GetInports',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.Channels.FromString,
                _registered_method=True)
        self.GetOutports = channel.unary_unary(
                '/cif.model_interface.ModelInterface/GetOutports',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.Channels.FromString,
                _registered_method=True)
        self.GetModelState = channel.unary_unary(
                '/cif.model_interface.ModelInterface/GetModelState',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.ModelStateResponse.FromString,
                _registered_method=True)
        self.GetParameters = channel.unary_unary(
                '/cif.model_interface.ModelInterface/GetParameters',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.Parameters.FromString,
                _registered_method=True)
        self.SetParameterValue = channel.unary_unary(
                '/cif.model_interface.ModelInterface/SetParameterValue',
                request_serializer=cif__model__interface__plugin__pb2.SetParameterRequest.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.GetParameterValue = channel.unary_unary(
                '/cif.model_interface.ModelInterface/GetParameterValue',
                request_serializer=cif__model__interface__plugin__pb2.GetParameterRequest.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.MonitoredData.FromString,
                _registered_method=True)
        self.GetSignals = channel.unary_unary(
                '/cif.model_interface.ModelInterface/GetSignals',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.GetSignalResponse.FromString,
                _registered_method=True)
        self.SetSignalList = channel.unary_unary(
                '/cif.model_interface.ModelInterface/SetSignalList',
                request_serializer=cif__model__interface__plugin__pb2.Signals.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.MonitorSignals = channel.unary_unary(
                '/cif.model_interface.ModelInterface/MonitorSignals',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.MonitoredData.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/cif.model_interface.ModelInterface/ListModels',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.ModelList.FromString,
                _registered_method=True)
        self.GetStatistics = channel.unary_unary(
                '/cif.model_interface.ModelInterface/GetStatistics',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__model__interface__plugin__pb2.Statistics.FromString,
                _registered_method=True)


class ModelInterfaceServicer(object):
    """This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

    """

    def GetInports(self, request, context):
        """List inport names for the loaded model  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOutports(self, request, context):
        """List the outport names for the loaded model  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelState(self, request, context):
        """Get the current state of the model  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameters(self, request, context):
        """List the exposed parameters for the loaded model  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetParameterValue(self, request, context):
        """Set a parameter value  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParameterValue(self, request, context):
        """Get a parameter value  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSignals(self, request, context):
        """List the exposed signals for the loaded model  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSignalList(self, request, context):
        """Set the signals to monitor  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorSignals(self, request, context):
        """Poll for the latest signal values  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """List of models in the default directory  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatistics(self, request, context):
        """Get statistics for the plugin  
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInports': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInports,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.Channels.SerializeToString,
            ),
            'GetOutports': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOutports,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.Channels.SerializeToString,
            ),
            'GetModelState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelState,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.ModelStateResponse.SerializeToString,
            ),
            'GetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameters,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.Parameters.SerializeToString,
            ),
            'SetParameterValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetParameterValue,
                    request_deserializer=cif__model__interface__plugin__pb2.SetParameterRequest.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'GetParameterValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameterValue,
                    request_deserializer=cif__model__interface__plugin__pb2.GetParameterRequest.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.MonitoredData.SerializeToString,
            ),
            'GetSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSignals,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.GetSignalResponse.SerializeToString,
            ),
            'SetSignalList': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSignalList,
                    request_deserializer=cif__model__interface__plugin__pb2.Signals.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'MonitorSignals': grpc.unary_unary_rpc_method_handler(
                    servicer.MonitorSignals,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.MonitoredData.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.ModelList.SerializeToString,
            ),
            'GetStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatistics,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__model__interface__plugin__pb2.Statistics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cif.model_interface.ModelInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cif.model_interface.ModelInterface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelInterface(object):
    """This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

    """

    @staticmethod
    def GetInports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/GetInports',
            cif__common__pb2.Empty.SerializeToString,
            cif__model__interface__plugin__pb2.Channels.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOutports(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/GetOutports',
            cif__common__pb2.Empty.SerializeToString,
            cif__model__interface__plugin__pb2.Channels.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/GetModelState',
            cif__common__pb2.Empty.SerializeToString,
            cif__model__interface__plugin__pb2.ModelStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/GetParameters',
            cif__common__pb2.Empty.SerializeToString,
            cif__model__interface__plugin__pb2.Parameters.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetParameterValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/SetParameterValue',
            cif__model__interface__plugin__pb2.SetParameterRequest.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParameterValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/GetParameterValue',
            cif__model__interface__plugin__pb2.GetParameterRequest.SerializeToString,
            cif__model__interface__plugin__pb2.MonitoredData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/GetSignals',
            cif__common__pb2.Empty.SerializeToString,
            cif__model__interface__plugin__pb2.GetSignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSignalList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/SetSignalList',
            cif__model__interface__plugin__pb2.Signals.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorSignals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/MonitorSignals',
            cif__common__pb2.Empty.SerializeToString,
            cif__model__interface__plugin__pb2.MonitoredData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/ListModels',
            cif__common__pb2.Empty.SerializeToString,
            cif__model__interface__plugin__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.model_interface.ModelInterface/GetStatistics',
            cif__common__pb2.Empty.SerializeToString,
            cif__model__interface__plugin__pb2.Statistics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
