# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cif_tag_monitor_plugin_pb2 as cif__tag__monitor__plugin__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cif_tag_monitor_plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TagMonitorStub(object):
    """This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDoubleTagValues = channel.unary_unary(
                '/cif.tag_monitor.TagMonitor/GetDoubleTagValues',
                request_serializer=cif__tag__monitor__plugin__pb2.TagValueRequest.SerializeToString,
                response_deserializer=cif__tag__monitor__plugin__pb2.DoubleTagValueResponse.FromString,
                _registered_method=True)


class TagMonitorServicer(object):
    """This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

    """

    def GetDoubleTagValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TagMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDoubleTagValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDoubleTagValues,
                    request_deserializer=cif__tag__monitor__plugin__pb2.TagValueRequest.FromString,
                    response_serializer=cif__tag__monitor__plugin__pb2.DoubleTagValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cif.tag_monitor.TagMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cif.tag_monitor.TagMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TagMonitor(object):
    """This demonstrates a simple gRPC service.  This service will allow setting a numeric value in the plugin and reading that value back.  

    """

    @staticmethod
    def GetDoubleTagValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.tag_monitor.TagMonitor/GetDoubleTagValues',
            cif__tag__monitor__plugin__pb2.TagValueRequest.SerializeToString,
            cif__tag__monitor__plugin__pb2.DoubleTagValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
