# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cif_common.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'cif_common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63if_common.proto\x12\ncif.common\"4\n\x0bTimingStats\x12\x0b\n\x03max\x18\x01 \x01(\x03\x12\x0b\n\x03min\x18\x02 \x01(\x03\x12\x0b\n\x03\x61vg\x18\x03 \x01(\x01\"C\n\x07Version\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\x12\x0b\n\x03\x66ix\x18\x03 \x01(\r\x12\r\n\x05\x62uild\x18\x04 \x01(\r\"9\n\x0cShortVersion\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\x12\x0b\n\x03\x66ix\x18\x03 \x01(\r\"7\n\x0bPluginNames\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\x13\n\x0bplugin_type\x18\x02 \x01(\t\"\'\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cif_common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMINGSTATS']._serialized_start=32
  _globals['_TIMINGSTATS']._serialized_end=84
  _globals['_VERSION']._serialized_start=86
  _globals['_VERSION']._serialized_end=153
  _globals['_SHORTVERSION']._serialized_start=155
  _globals['_SHORTVERSION']._serialized_end=212
  _globals['_PLUGINNAMES']._serialized_start=214
  _globals['_PLUGINNAMES']._serialized_end=269
  _globals['_STATUS']._serialized_start=271
  _globals['_STATUS']._serialized_end=310
  _globals['_EMPTY']._serialized_start=312
  _globals['_EMPTY']._serialized_end=319
# @@protoc_insertion_point(module_scope)
