# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cif_common_pb2 as cif__common__pb2
import cif_plugin_core_pb2 as cif__plugin__core__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cif_plugin_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginCoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/cif.plugincore.PluginCore/Start',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.Pause = channel.unary_unary(
                '/cif.plugincore.PluginCore/Pause',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/cif.plugincore.PluginCore/Stop',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.RefreshStatistics = channel.unary_unary(
                '/cif.plugincore.PluginCore/RefreshStatistics',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/cif.plugincore.PluginCore/UpdateConfig',
                request_serializer=cif__plugin__core__pb2.Configuration.SerializeToString,
                response_deserializer=cif__common__pb2.Status.FromString,
                _registered_method=True)
        self.GetStatusData = channel.unary_unary(
                '/cif.plugincore.PluginCore/GetStatusData',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__plugin__core__pb2.StatusData.FromString,
                _registered_method=True)
        self.GetVersion = channel.unary_unary(
                '/cif.plugincore.PluginCore/GetVersion',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.Version.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/cif.plugincore.PluginCore/GetConfig',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__plugin__core__pb2.Configuration.FromString,
                _registered_method=True)
        self.GetOverrides = channel.unary_unary(
                '/cif.plugincore.PluginCore/GetOverrides',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__plugin__core__pb2.PluginOverrides.FromString,
                _registered_method=True)
        self.GetNames = channel.unary_unary(
                '/cif.plugincore.PluginCore/GetNames',
                request_serializer=cif__common__pb2.Empty.SerializeToString,
                response_deserializer=cif__common__pb2.PluginNames.FromString,
                _registered_method=True)


class PluginCoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pause(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatusData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOverrides(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'Pause': grpc.unary_unary_rpc_method_handler(
                    servicer.Pause,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'RefreshStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshStatistics,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=cif__plugin__core__pb2.Configuration.FromString,
                    response_serializer=cif__common__pb2.Status.SerializeToString,
            ),
            'GetStatusData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatusData,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__plugin__core__pb2.StatusData.SerializeToString,
            ),
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.Version.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__plugin__core__pb2.Configuration.SerializeToString,
            ),
            'GetOverrides': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverrides,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__plugin__core__pb2.PluginOverrides.SerializeToString,
            ),
            'GetNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNames,
                    request_deserializer=cif__common__pb2.Empty.FromString,
                    response_serializer=cif__common__pb2.PluginNames.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cif.plugincore.PluginCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cif.plugincore.PluginCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginCore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/Start',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pause(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/Pause',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/Stop',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/RefreshStatistics',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/UpdateConfig',
            cif__plugin__core__pb2.Configuration.SerializeToString,
            cif__common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatusData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/GetStatusData',
            cif__common__pb2.Empty.SerializeToString,
            cif__plugin__core__pb2.StatusData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/GetVersion',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.Version.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/GetConfig',
            cif__common__pb2.Empty.SerializeToString,
            cif__plugin__core__pb2.Configuration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOverrides(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/GetOverrides',
            cif__common__pb2.Empty.SerializeToString,
            cif__plugin__core__pb2.PluginOverrides.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cif.plugincore.PluginCore/GetNames',
            cif__common__pb2.Empty.SerializeToString,
            cif__common__pb2.PluginNames.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
