syntax = "proto3";

import "cif_common.proto";
import "cif_management_common.proto";

package cif.channelcore;

service ChannelCore {
  rpc GetChannels (GetChannelsRequest) returns (GetChannelsResponse) {}
  rpc SetConnection (SetConnectionRequest) returns (SetConnectionResponse) {}
  //This is only supported on tags.
  rpc SetForce (SetForceRequest) returns (SetForceResponse) {}
  //This is needed when the publisher needs to provide information to support a subscriber.  For instance if a new publisher needs to be
  // created for a 1-1 FIFO or if backpressure is used and the publisher needs to provide the handles.
  rpc CreateFIFOInstance (CreateFIFOInstanceRequest) returns (CreateFIFOInstanceResponse) {}  
  //This is used to destroy or disconnect a subscriber after the CreateFIFOInstance was used.  
  rpc DestroyFIFOInstance (DestroyFIFOInstanceRequest) returns (DestroyFIFOInstanceResponse) {} 
}

message GetChannelsRequest {}

message GetChannelsResponse {
  cif.management_common.Channels channels = 1;
}

message SetConnectionRequest {
  string subscriber_name = 1;
  string publisher_name = 2;
  bytes custom_connect = 3;  //This field allows passing free form custom data needed to perform specific connection operations.  It's implementation will be type specific.  
}

message SetConnectionResponse {
  cif.common.Status status = 1;
}

message CreateFIFOInstanceRequest {
  string publisher_name = 1; //The name of the existing FIFO to create a new instance for the subscriber
  bool retry_on_timeout = 2; //Is the subscriber applying backpressure to control the rate of the publisher.  On FIFO full (timeout) the publisher will retry until space is available.
  //This is normally only used for file read publishers.  This value is applied as an AND with the publisher configuration (will only apply backpressure if publisher is configured for backpressure support).
  uint32 bytes_per_message_override = 3;  //A value of 0 indicates don't override.  This is the number of bytes in a single payload added to the FIFO buffer.  
  uint32 message_per_fifo_override = 4;  //A value of 0 indicates don't override.  This is the number of "messages" in the FIFO buffer.  
  bytes custom_data = 5;  //This field allows passing free form custom data needed to perform specific connection operations.  It's implementation will be type specific. 
}

message CreateFIFOInstanceResponse {
  FIFOReference fifo_reference = 1;
  cif.common.Status status =2;
}

message FIFOReference {
  string publisher_instance_name = 1; //Unique instance name of the multi-writer FIFO publisher.
  bytes custom_connect = 2; //This field allows passing free form custom data needed to perform specific connection operations.  It's implementation will be type specific. 
}

message DestroyFIFOInstanceRequest {
  string publisher_instance_name = 1; //Unique instance name of the multi-writer FIFO publisher.
}

message DestroyFIFOInstanceResponse {
  cif.common.Status status = 1;
}

message SetForceRequest {
  string channel_name = 1;
  bool force = 2;
  bytes force_data = 3;  //Flattened data for the forced value.  Values are big endian.  
}

message SetForceResponse {
  cif.common.Status status = 1;
}